### ISSUE TITLE
browserVersion: insiders fails

### ISSUE THREAD

**Issue by kgartland-rstudio** [webdriverio-community/wdio-vscode-service#124]
Version: `wdio-vscode-service": "^6.1.0`

When running with `browserVersion: "insiders"` I hit the following error:

> 2024-06-21T15:19:35.831Z INFO @wdio/local-runner: shutting down
SevereServiceError in "onPrepare"
SevereServiceError:
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't set up VSCode: Invalid version main
    at VSCodeServiceLauncher._downloadVSCode (file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/wdio-vscode-service/src/launcher.ts:192:19)
    at async VSCodeServiceLauncher._setupVSCodeDesktop (file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/wdio-vscode-service/src/launcher.ts:175:47)
    at async VSCodeServiceLauncher.onPrepare (file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/wdio-vscode-service/src/launcher.ts:95:17)
    at async file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/@wdio/cli/build/utils.js:42:17
    at async Promise.all (index 0)
    at async Launcher.run (file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/@wdio/cli/build/launcher.js:93:13)
Stopping runner...
    at file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/@wdio/cli/build/utils.js:58:35
    at async Launcher.run (file:///Users/kgartland/work/publishing-client/test/vscode-ui/node_modules/@wdio/cli/build/launcher.js:93:13)

Running with `browserVersion: "stable" works as expected.

**Comment by sij1nk** [comment]
`browserVersion: "insiders"` similarly does not work if `browserName: "chrome"`

Using the following `wdio.conf.ts`:

```ts
import type { Options } from "@wdio/types";
export const config: Options.Testrunner = {
  runner: "local",
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      project: "./tsconfig.json",
      transpileOnly: true,
    },
  },
  specs: ["./test/specs/**/*.ts"],
  exclude: [],
  maxInstances: 10,
  capabilities: [
    {
      browserName: "chrome",
      browserVersion: "insiders",
      "wdio:vscodeOptions": {
        userSettings: {
          "editor.fontSize": 14,
        },
      },
    },
  ],
  logLevel: "info",
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ["vscode"],

  framework: "mocha",

  reporters: ["spec"],

  mochaOpts: {
    ui: "bdd",
    timeout: 60000,
  },
};
```

Produces the following error: 
[error.txt](https://github.com/user-attachments/files/16453890/error.txt)

I traced this back to https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/launcher.ts#L267 : the string `insiders` is inserted into `VSCODE_WEB_STANDALONE`, but the resulting URL leads nowhere. It works if we insert the string `insider` 

https://update.code.visualstudio.com/api/update/web-standalone/insiders/latest
https://update.code.visualstudio.com/api/update/web-standalone/insider/latest

Not sure if there's anything else, I did not debug this extensively

**Comment by jmccure** [comment]
I think this can be closed
