### ISSUE TITLE
Unable to get wdio-vscode-service working from workspace directory with a long path

### ISSUE THREAD

**Issue by fjakobs** [webdriverio-community/wdio-vscode-service#32]
I made a very bare bones example based on your docs. It doesn't work from my normal project folder `/Users/fabian.jakobs/Desktop/Workspaces/wdio` but it does work when copying it to `/tmp` and running it from there. I was running into similar issues before where the full VSCode executable path had to be below a certain length but this time I'm unable to fix it.

Setting `cachePath` to `/tmp` also didn't help.

VSCode never even starts in the first case.

**Comment by fjakobs** [comment]
Example code

[wdio.zip](https://github.com/webdriverio-community/wdio-vscode-service/files/9300651/wdio.zip)

**Comment by fjakobs** [comment]
Logs

```
% npm run wdio

> wdio@1.0.0 wdio
> wdio run test/wdio.conf.ts


Execution of 1 workers started at 2022-08-10T14:01:23.550Z

(node:89204) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2022-08-10T14:01:23.845Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-08-10T14:01:23.850Z INFO wdio-vscode-service/launcher: Fetch releases from https://update.code.visualstudio.com/api/releases/stable
2022-08-10T14:01:24.534Z INFO wdio-vscode-service/launcher: Download Chromedriver (v100.0.4896.60)
2022-08-10T14:01:25.904Z INFO wdio-vscode-service/launcher: Download VSCode binary (1.69.1)
Found existing install in /Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1. Skipping download
2022-08-10T14:01:25.908Z INFO chromedriver: Start Chromedriver (/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/chromedriver-100.0.4896.60) with args --port=9515 --url-base=/
2022-08-10T14:01:26.164Z INFO chromedriver: Starting ChromeDriver 100.0.4896.60 (6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}) on port 9515
2022-08-10T14:01:26.164Z INFO chromedriver: Only local connections are allowed.
2022-08-10T14:01:26.164Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-08-10T14:01:26.165Z INFO chromedriver: ChromeDriver was started successfully.
2022-08-10T14:01:26.227Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-08-10T14:01:26.228Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,test/wdio.conf.ts
[0-0] 2022-08-10T14:01:26.439Z INFO @wdio/local-runner: Run worker command: run
[0-0] (node:89209) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
[0-0] (Use `node --trace-warnings ...` to show where the warning was created)
[0-0] 2022-08-10T14:01:26.810Z INFO wdio-vscode-service: Start VSCode proxy server on port 55454
[0-0] 2022-08-10T14:01:26.810Z INFO wdio-vscode-service: Setting up VSCode directory at /var/folders/ym/mh9vt0j15m5cdv5t0m02cf6r0000gp/T/tmp-89209-cH3VslPLIhop/settings/User
[0-0] 2022-08-10T14:01:26.812Z INFO wdio-vscode-service: Start VSCode: /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js --no-sandbox --disable-updates --skip-welcome --skip-release-notes --disable-workspace-trust --disable-extensions --extension-development-path=/Users/fabian.jakobs/Desktop/Workspaces/wdio --extension-tests-path=/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/proxy/index.js --user-data-dir=/var/folders/ym/mh9vt0j15m5cdv5t0m02cf6r0000gp/T/tmp-89209-cH3VslPLIhop/settings --extensions-dir=/var/folders/ym/mh9vt0j15m5cdv5t0m02cf6r0000gp/T/tmp-89209-cH3VslPLIhop/extensions --vscode-binary-path=/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1/Visual Studio Code.app/Contents/MacOS/Electron
[0-0] RUNNING in chrome - /test/specs/example.e2e.ts
[0-0] 2022-08-10T14:01:26.917Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-08-10T14:01:26.943Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-08-10T14:01:26.943Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: '1.69.1',
[0-0]       'wdio:vscodeOptions': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: '1.69.1',
[0-0]     'wdio:vscodeOptions': {
[0-0]       extensionPath: '/Users/fabian.jakobs/Desktop/Workspaces/wdio',
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1/Visual Studio Code.app/Contents/MacOS/Electron'
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js',
[0-0]       args: [Array],
[0-0]       windowTypes: [Array]
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2022-08-10T14:01:27.060Z WARN webdriver: Request failed with status 500 due to unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0] 2022-08-10T14:01:27.060Z INFO webdriver: Retrying 1/3
[0-0] 2022-08-10T14:01:27.060Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-08-10T14:01:27.060Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: '1.69.1',
[0-0]       'wdio:vscodeOptions': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: '1.69.1',
[0-0]     'wdio:vscodeOptions': {
[0-0]       extensionPath: '/Users/fabian.jakobs/Desktop/Workspaces/wdio',
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1/Visual Studio Code.app/Contents/MacOS/Electron'
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js',
[0-0]       args: [Array],
[0-0]       windowTypes: [Array]
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2022-08-10T14:01:27.168Z WARN webdriver: Request failed with status 500 due to unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0] 2022-08-10T14:01:27.168Z INFO webdriver: Retrying 2/3
[0-0] 2022-08-10T14:01:27.168Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-08-10T14:01:27.168Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: '1.69.1',
[0-0]       'wdio:vscodeOptions': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: '1.69.1',
[0-0]     'wdio:vscodeOptions': {
[0-0]       extensionPath: '/Users/fabian.jakobs/Desktop/Workspaces/wdio',
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1/Visual Studio Code.app/Contents/MacOS/Electron'
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js',
[0-0]       args: [Array],
[0-0]       windowTypes: [Array]
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2022-08-10T14:01:27.275Z WARN webdriver: Request failed with status 500 due to unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0] 2022-08-10T14:01:27.276Z INFO webdriver: Retrying 3/3
[0-0] 2022-08-10T14:01:27.276Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-08-10T14:01:27.276Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: '1.69.1',
[0-0]       'wdio:vscodeOptions': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: '1.69.1',
[0-0]     'wdio:vscodeOptions': {
[0-0]       extensionPath: '/Users/fabian.jakobs/Desktop/Workspaces/wdio',
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/.wdio-vscode-service/vscode-darwin-arm64-1.69.1/Visual Studio Code.app/Contents/MacOS/Electron'
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js',
[0-0]       args: [Array],
[0-0]       windowTypes: [Array]
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2022-08-10T14:01:27.383Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0] 2022-08-10T14:01:27.383Z ERROR webdriver: unknown error: unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0]     at getErrorFromResponseBody (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/utils.js:198:12)
[0-0]     at NodeJSRequest._request (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/utils.js:68:20)
[0-0]     at async Function.newSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at async Runner._startSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2022-08-10T14:01:27.385Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] unknown error: Chrome failed to start: exited abnormally.
[0-0]   (unknown error: DevToolsActivePort file doesn't exist)
[0-0]   (The process started from chrome location /Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/wdio-vscode-service/dist/chromium/index.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[0-0]     at startWebDriverSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/utils.js:73:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Function.newSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at async Runner._startSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/fabian.jakobs/Desktop/Workspaces/wdio/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] FAILED in chrome - /test/specs/example.e2e.ts
2022-08-10T14:01:27.491Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-08-10T14:01:27.492Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:03 

2022-08-10T14:01:27.492Z INFO @wdio/local-runner: Shutting down spawned worker
2022-08-10T14:01:27.743Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-08-10T14:01:27.744Z INFO @wdio/local-runner: shutting down
fabian.jakobs@NM4Y0F6NN6 wdio % 
```

**Comment by christian-bromann** [comment]
It seems like it is unrelated to the length of the path. I ran the script in:

```
❯ cd onesuperlongpath/withmoresuperlongsubdirectories/andIcangetoneandoneandoneandoneandone/thisisfunletsseehwatcomesout/wdio/
❯ npm run wdio
``` 

And it was running successfully. So my hunch is that there is some sort of access right/privilege issue starting a port from a process that resides in the Desktop directory. Is there any reasons why your dev environment is within the Desktop folder?

**Comment by fjakobs** [comment]
It's indeed the desktop directory. Trying to figure out how to fix this.

**Comment by fjakobs** [comment]
I assume it has something to do with the new folder protections in OSX. Couldn't find a way to fix it so moved my `Workspaces` folder out of my `Desktop` to prevent similar issues in the future.
